export const MESSAGES = 'LOADINGS';
export const LOADING = 'LOADING';
export const AUTHENTICATE = 'AUTHENTICATE';
export const DEAUTHENTICATE = 'DEAUTHENTICATE';
export const RESTORE_AUTH_STATE  = 'RESTORE_AUTH_STATE';
