export const HUMAN_RESOURCE = 'HUMAN_RESOURCE';
export const INVENTORY = 'INVENTORY';
export const SALES_AND_MARKETING = 'SALES_AND_MARKETING';
export const PURCHASE = 'PURCHASE';
export const FINANCE_AND_ACCOUNTING = 'FINANCE_AND_ACCOUNTING';
export const CUSTOMES_RELATIONSHIP_MANAGEMENT = 'CUSTOMES_RELATIONSHIP_MANAGEMENT';
export const SUPPLY_CHAIN_MANAGEMENT = 'SUPPLY_CHAIN_MANAGEMENT';

export const moduleTypes = {
    HUMAN_RESOURCE,
    INVENTORY,
    SALES_AND_MARKETING,
    PURCHASE,
    FINANCE_AND_ACCOUNTING,
    CUSTOMES_RELATIONSHIP_MANAGEMENT,
    SUPPLY_CHAIN_MANAGEMENT,
};
